### ISSUE TITLE
Only ./bin files - Source files?

### ISSUE THREAD

**Issue by abrarShariar** [johannesboyne/gomon#6]
In this repo there is only the `bin` directory. What about the source files? Those are necessary for any PR, I guess. :) 

I am thinking of creating a folder structure which will also benefit anyone who will contribute to this repo in the future.

**Comment by johannesboyne** [comment]
it's Nodejs ;) thus no realy binaries more a "convenient" way of placing executable node programs. Thus there is the source code!
